### PR TITLE
Fix: results bar chart equal preference all zeroes

### LINKED ISSUE #756: Update ResultsBarChart to display 0 without overlapping with category names
> That said we can open a new issue for fixing graphs when the have zeros. Currently the zeros overlap with the category titles and it's messy.

 _Originally posted by @ArendPeter in [#741](https://github.com/Equal-Vote/star-server/issues/741#issuecomment-2611297004)_

### PR DESCRIPTION
**Pull request by recursivesquircle**
## Description
Adds a tick margin to the equal preferences results bar chart when equal preference votes are all zeroes to fix overlapping text.

## Screenshots / Videos (frontend only) 

> Be sure to include both desktop and mobile views (mobile could be as low as 320 px wide) 

image
image
image
image

Closes #756

### CODE REVIEW

File: packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx [hunk 1]
```diff
@@ -1,6 +1,10 @@
 import { Bar, Cell, ComposedChart, LabelList, Legend, Line, ResponsiveContainer, XAxis, YAxis } from "recharts";
 import { CHART_COLORS, truncName } from "~/components/util";
 
+export enum ResultsBarChartType {
```
Comment (ArendPeter) [inline packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx:4]: nitpick: we've usually use string literals instead of enums, and then using typescript to force the list of strings. More details at https://devsparks.goooseman.dev/hacks/20240715-use-string-literals-not-enums/

That said, I don't think you need the resultsBarChartType at all here. This change will be useful in a variety of contexts in addition to equal preferences. For example, we saw the same issue occur on the scoring chart in 
https://github.com/Equal-Vote/star-server/issues/741

**Review by ArendPeter — COMMENTED** [review]
Looks great, thank you for the fix!

I think this fix will be useful more generally than equal preferences so it can opened up more

File: packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx (hunk 1 above)
Comment (recursivesquircle) [reply packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx:4]: Okay I will remove the type.  I take it that assumes that any other bar chart that takes all zeroes is going to look right with that margin added?  And I will take note of the string literal over enum preference that you have

File: packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx [hunk 2]
```diff
@@ -2,22 +2,46 @@ import { useState } from "react";
 import { Bar, Cell, ComposedChart, LabelList, Legend, Line, ResponsiveContainer, XAxis, YAxis } from "recharts";
 import { CHART_COLORS, formatPercent, truncName } from "~/components/util";
 
-export default ({
+
+interface ResultsBarChartData {
```
Comment (ArendPeter) [inline packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx:6]: Nice work adding the types here!

**Review by ArendPeter — APPROVED** [review]
Looks great, approved!

File: packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx (hunk 1 above)
Comment (ArendPeter) [reply packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx]: Yep, I think they should all look good with the margin logic

**Comment by ArendPeter** [comment]
The build error is because VoterErrorStats doesn't use the format of the new typescript interface.

I pushed a change so that the convention complies, so one more rebase should get the build passing on this PR

https://github.com/Equal-Vote/star-server/commit/80545265c9a6c43290d2cc00771708af39a8740c
