### PR TITLE
Forced race title to be unique and fixed bug where races were not being validated for the first two

### LINKED ISSUE #503: Race name not unique (low priority)
race name not unique - are we ok with this?

Low priority ...

We can have two races with the same title:

https://dev.star.vote/Election/6774012d-d161-49b1-9552-bf965600c681/admin
image

### PR DESCRIPTION
**Pull request by csamuele**
## Screenshots / Videos (frontend only) 
image
image

> Be sure to include both desktop and mobile views (mobile could be as low as 320 px wide) 

## Related Issues
``fixes #503``
> For example, add ``fixes #10`` to close issue #10

### CODE REVIEW

File: packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx [hunk 1]
```diff
@@ -50,7 +50,6 @@ export const useEditRace = (race, race_index) => {
     const validatePage = () => {
         let isValid = true
         let newErrors: any = {}
-        if (election.races.length > 1) {
```
Comment (ArendPeter) [inline packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx:53]: Me and Sam discussed removing this line. I believe this was a hold over from earlier UI iterations, and we opted to remove it since it was weakening the validation on the initial races that were created

File: packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx [hunk 2]
```diff
@@ -63,7 +62,18 @@ export const useEditRace = (race, race_index) => {
                 newErrors.raceDescription = 'Race title must be less than 1000 characters';
                 isValid = false;
             }
-        }
+            if (election.races.some(race => {
```
Comment (ArendPeter) [inline packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx:65]: Neat, I don't think I've used some() before but it looks handy

**Review by ArendPeter — APPROVED** [review]
Looks great!

File: packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx (hunk 2 above)
Comment (csamuele) [reply packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx:65]: I love all the array methods!
