### PR TITLE
fix: Make admin preliminary results depend on election setting

### LINKED ISSUE #1056: BV2105 - Favorite ice cream (Bloc STAR) - demo election (unlimitted voting)
### regression test "create a demo election" fails  (flexibility and relaxed rules across the board, no limits on ballot viewing, etc)
As a result of work on "Editable ballots" https://github.com/Equal-Vote/bettervoting/issues/979 - we broke  "demo elections" (all flexibility and relaxed rules across the board, no limits on ballot viewing, etc)
Now we are unable to download JSON, CSV or view "Race Details"
video: https://youtu.be/dxLxu9UgkuU
election link: https://bettervoting.com/2pgjb9
doc: BV2105 - Favorite ice cream (Bloc STAR)  - https://docs.google.com/document/d/1TEo6EaitKT9zFKqOD_YXzBlq2SQ_RA7cu7Ckpo3W8EY/edit?tab=t.0

error message: Error making request: 401: Ballot access only permited when public results are enabled or election has closed (ec88bf89)

Image

### LINKED ISSUE #1058: Editable Ballots - Fix broken results view
- admin page should not have a results button when an election is open and preliminary results is not enabled
- it should not be possible to get results by api under these conditions either
- preliminary results should be enabled by default for open elections

See #1056

### PR DESCRIPTION
**Pull request by JonBlauvelt**
## Description
- remove results button from admin page when election is not closed and prelim results is disabled
- block results API when prelim results is disabled and election is not closed
- discard unsaved election settings on 'cancel'
- change from edit to view icon and disable form for election settings when election leaves draft state
- only show close button for admin race view when editing is disabled and fix form elements that were not disabled
- make candidate order randomized by default
- fix some noisy console warnings
- clean up election settings form
- remove commented code

* Includes some unilateral and opinionated changes to the election form and race form - welcoming thoughts/comments/objections/vitriol*

## Screenshots / Videos (frontend only) 

https://github.com/user-attachments/assets/36835b71-7850-46cc-a44c-494354f852ac

https://github.com/user-attachments/assets/c94ec451-3dc5-4082-a495-48c459c69f0a

https://github.com/user-attachments/assets/75002014-e8df-47dc-a766-648fbcc52133

https://github.com/user-attachments/assets/5609ae82-7809-4bb0-931a-3f9238b4c54d

## Related Issues

fixes #1058 
fixes #1056

### CODE REVIEW

File: packages/frontend/src/components/ElectionForm/ElectionSettings.tsx [hunk 1]
```diff
@@ -27,25 +29,26 @@ export default function ElectionSettings() {
...
 
     const [editedElectionSettings, setEditedElectionSettings] = useState(election.settings);
-    const [editedIsPublic, setEditedIsPublic] = useState(election.is_public);
     const [publicResults, setPublicResults] = useState(election.settings.public_results);
     const [ballotUpdates, setBallotUpdates] = useState(election.settings.ballot_updates);
-    const [ballotUpdatesDisabled, setBallotUpdatesDisabled] = useState(!ballotUpdatesConditionsMet);
-    const [publicResultsDisabled, setPublicResultsDisabled] = useState(false);
-    const [publicResultsDisabledMsg, setPublicResultsDisabledMsg] = useState(undefined);
-    const [ballotUpdatesDisabledMsg, setBallotUpdatesDisabledMsg] = useState(undefined);
+    const [ballotUpdatesDisabled, setBallotUpdatesDisabled] = useState(!ballotUpdatesConditionsMet || election.settings.public_results);
```
Comment (ArendPeter) [inline packages/frontend/src/components/ElectionForm/ElectionSettings.tsx]: nit, these 2 lines could use a comment explaining while public results is being passed in for ballot updates and vice versa. It would be easy for someone in the future to swap them assuming it's a typo

File: packages/frontend/src/components/ElectionForm/ElectionSettings.tsx [hunk 2]
```diff
@@ -74,11 +80,10 @@ export default function ElectionSettings() {
         }
         const success = await updateElection(election => {
             election.settings = editedElectionSettings
-            election.is_public = editedIsPublic
         })
         if (!success) return false
         await refreshElection()
-        handleClose()
```
Comment (ArendPeter) [inline packages/frontend/src/components/ElectionForm/ElectionSettings.tsx]: Why was this removed? Wouldn't syncState still need to be called as a side effect?
